### PR TITLE
fix -moz-box behavior

### LINKED ISSUE #154: Style bug (Firefox >= v71)
issue

### PR DESCRIPTION
**Pull request by fmeyertoens**
This should fix #154

### CODE REVIEW

**Comment by guyjin** [comment]
Holla, that works a treat.  Well done.

**Comment by fmeyertoens** [comment]
I can't reproduce that on Windows. Which OS or custom theme are you using?

**Comment by redfoxseattle** [comment]
I'm on OS X Mojave and Firefox Developer Edition. I'm using the Windows 95/98 classic grey menu colour theme. But it seemed to occur with any theme I chose.

**Comment by fmeyertoens** [comment]
Can you check the value of the `--tab-bgcolor` and `--toolbar-bgcolor` variables? I'm pretty sure that this only occurs when one of them has an alpha value other than 1.

**Comment by redfoxseattle** [comment]
I couldn't find the --tab-bgcolor variable. --toobar-bgcolor didn't have any changes to the opacity. I'm just using exactly what I found here, no changes.

--toolbar-bgcolor: #fff !important;

**Comment by redfoxseattle** [comment]
I'm seeing this on any theme that's light gray. Themes with white or dark tabs look fine.

**Comment by fmeyertoens** [comment]
You should be able to find the `--tab-bgcolor` variable on the `vbox class="tab-background"` element because there it is used as the background color (that should be the light gray color of your tabs). On my setup it is equal to `--toolbar-bgcolor` because of this line:
https://github.com/muckSponge/MaterialFox/blob/9ba6b1b23016eb31f19d2fb68f926f69aeeb2ed0/chrome/tabbar/tabbar.css#L206-L208
It seems not to be the case with your setup because the tab is clearly not white (#fff).

**Pull request merged**
