### PR TITLE
Adds Fullscreen Fixes

### PR DESCRIPTION
**Pull request by Trystanr**

### CODE REVIEW

**Comment by muckSponge** [comment]
The space above tab bar is actually already defined when you check the drag space checkbox in the customize menu. I've added/updated the padding at the start of the tab bar in [windows-improvements](https://github.com/muckSponge/MaterialFox/tree/windows-improvements). I'll be trying to merge this back into master once I've ensured that the changes don't negatively impact macOS. I took a different approach by forcing ```.titlebar-placeholder[type=pre-tabs] { display: -moz-box }``` and setting width to 8px.

**Comment by Trystanr** [comment]
The space above tab bar works in windowed mode but doesn't exist once in fullscreen mode.

**Comment by muckSponge** [comment]
This reflects Chrome behaviour, at least on Windows. Haven't checked macOS yet.
________________________________

**Comment by Trystanr** [comment]
Having a space in fullscreen mode is the functionality on macOS.

**Comment by muckSponge** [comment]
If you're willing to checkout windows-improvements branch, this should now be incorporated. I went about it in a slightly different way so I won't merge the pull request but thank you for prodding me in the right direction here, wasn't aware of some of the discrepancies. Should be in master in a few days.

**Pull request closed without merging**
